---
- name: Simple Webhook Rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Trigger Job on Webhook payload
      condition: event.payload is defined
      action:
        run_job_template:
          name: Simple EDA Test Template
          organization: Default
